# -*- coding: utf-8 -*-
"""e-ccmmerce-linha-luxo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWtGXJcyTF0mxCokLW8HX8oiJOGc3fbL
"""

class SistemaClientes:
    def __init__(self):
        self._pilha_sessoes = []
        self._clientes = {}

    def registrar(self, email: str, nome: str, senha: str) -> bool:
        if email in self._clientes:
            return False
        self._clientes[email] = {"nome": nome, "senha": senha}
        return True

    def login(self, email: str, senha: str) -> bool:
        dados = self._clientes.get(email)
        if not dados or dados["senha"] != senha:
            return False
        self._pilha_sessoes.append(email)
        return True

    def logout(self) -> str | None:
        if not self._pilha_sessoes:
            return None
        return self._pilha_sessoes.pop()

    def cliente_atual(self) -> str | None:
        return self._pilha_sessoes[-1] if self._pilha_sessoes else None