#4# -*- coding: utf-8 -*-
"""Formas de pagamento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ts7dC66ioNQhKn3Crqsk_4XpR_BMBQm
"""

def mostrar_formas_pagamento():
    print("Formas de pagamento disponíveis:")
    print("1 - Cartão de débito")
    print("2 - Cartão de Crédito")
    print("3 - Pix")

def calcular_pagamento(valor, opcao):
    if opcao in [1, 2, 3]:
        return valor  # Sem alteração no valor
    else:
        print("Opção inválida.")
        return None

valor_total = float(input("Digite o valor total da compra: R$ "))
mostrar_formas_pagamento()
opcao_escolhida = int(input("Escolha a forma de pagamento (1-3): "))
valor_final = calcular_pagamento(valor_total, opcao_escolhida)

if valor_final is not None:
    print(f"Forma de pagamento escolhida: {opcao_escolhida}")
    print(f"Valor final a pagar: R$ {valor_final:.2f}")
