# -*- coding: utf-8 -*-
"""Formas de pagamento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ts7dC66ioNQhKn3Crqsk_4XpR_BMBQm
"""

def mostrar_formas_pagamento(formas):
    print("Formas de pagamento disponíveis:")
    for i, forma in enumerate(formas, start=1):
        print(f"{i} - {forma}")

def calcular_pagamento(valor, opcao, formas):
    if 1 <= opcao <= len(formas):
        return valor  # Sem alteração no valor
    else:
        print("Opção inválida.")
        return None

formas_pagamento = ["Cartão de débito", "Cartão de crédito", "Pix"]

valor_total = float(input("Digite o valor total da compra: R$ "))
mostrar_formas_pagamento(formas_pagamento)
opcao_escolhida = int(input("Escolha a forma de pagamento (1-3): "))
valor_final = calcular_pagamento(valor_total, opcao_escolhida, formas_pagamento)

if valor_final is not None:
    forma_escolhida = formas_pagamento[opcao_escolhida - 1]
    print(f"Forma de pagamento escolhida: {forma_escolhida}")
    print(f"Valor final a pagar: R$ {valor_final:.2f}")