# -*- coding: utf-8 -*-
"""AV60pontos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ogAcKxLEHM--pqYr7msX8Yd9dYqlqxUr
"""

print('================================================================================================================================================================')
print('                                                                  LISTA DE ROUPAS                                                                               ')
print('================================================================================================================================================================')

roupas_dict = {'blusa de frio': ('19,99', 'cashmere'),
               'blusa de calor': ('17,00', 'algodão'),
               'calça jeans':('30,00', 'jeans'),
               'short': ('15,00', 'jeans'),
               'calca legging':('20,00', 'Poliéster'),
               'luva': ('15,00', 'algodão'),
               'gorro': ('15,00', 'algodão'),
               'chapeu': ('10,00', 'algodão')}

for produto in roupas_dict.keys():
    print(produto)
produto = str(input('Digite o produto que você deseja visualizar: ')).lower()
if produto in roupas_dict:
  print(roupas_dict[produto])

else:
    print("Perdão, ainda não temos esse produto!")
