# -*- coding: utf-8 -*-
"""LL_solucoes_carrinho_de_compras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZzUh9jGY7-I754jhyPegdRbFoo8DWGe

### **Carrinho de Compras**
"""

class Cart(list):
  def __init__(self, *args):
    super().__init__(args)
  def add_item(self, item):
    self.append(item)
  def clear_cart(self):
    for i in self:
      self.remove(i)
  def rem_item(self, item):
    try:
      self.remove(item)
    except ValueError:
      print("Item não encontrado")
  def view_cart(self):
    if not self:
      print("Seu carrinho está vazio")
    else:
      for i in self:
       print(i)

meu_carrinho = Cart()